import { test, expect } from '@playwright/test';
import { PDFDocument } from 'pdf-lib';
import { getDocument } from 'pdfjs-dist/legacy/build/pdf.mjs';
import { readFile } from 'node:fs/promises';
import { readPdfTables } from '../src/services/pdfTableService.js';

test('table structure and cell formatting survive PDF save and reopen', async ({ page }) => {
  test.setTimeout(120_000);
  const source = await PDFDocument.create();
  source.addPage([500, 500]);
  await page.goto('/');
  await page.locator('input[type="file"]').first().setInputFiles({
    name: 'table-source.pdf', mimeType: 'application/pdf', buffer: Buffer.from(await source.save())
  });
  const pdfPage = page.locator('.pdf-page[data-page-number="1"]');
  await expect(pdfPage.locator('.textLayer')).toHaveAttribute('data-rendered', 'true');
  await page.locator('.pdf-edit-mode-toggle button').last().click();
  await page.getByRole('button', { name: '표 추가' }).click();
  const bounds = await pdfPage.boundingBox();
  const scale = bounds.width / 500;
  await page.mouse.move(bounds.x + 80 * scale, bounds.y + 80 * scale);
  await page.mouse.down();
  await page.mouse.move(bounds.x + 330 * scale, bounds.y + 230 * scale, { steps: 8 });
  await page.mouse.up();
  const table = pdfPage.locator('.pdf-table-object');
  await expect(table).toBeVisible();
  await expect(page.locator('.pdf-table-toolbar')).toHaveCount(0);
  await table.getByRole('textbox', { name: '1행 1열' }).click();
  await expect(page.locator('.pdf-table-toolbar')).toBeVisible();
  await table.getByRole('textbox', { name: '1행 1열' }).fill('제목');
  await table.getByRole('textbox', { name: '1행 2열' }).click({ modifiers: ['Shift'] });
  await page.getByRole('button', { name: '셀 병합' }).click();
  await expect(table.locator('.pdf-table-cell')).toHaveCount(8);
  await table.getByRole('textbox', { name: '2행 1열' }).click();
  await page.getByRole('tab', { name: '셀 서식' }).click();
  await page.getByRole('button', { name: '굵게' }).click();
  await page.getByLabel('셀 가로 정렬').selectOption('right');
  await page.getByRole('tab', { name: '크기' }).click();
  await page.getByLabel('선택한 열 너비').fill('95');
  await table.getByRole('textbox', { name: '3행 1열' }).evaluate((element) => {
    const data = new DataTransfer();
    data.setData('text/plain', '첫째\t1\n둘째\t2');
    element.dispatchEvent(new ClipboardEvent('paste', { bubbles: true, cancelable: true, clipboardData: data }));
  });
  await expect(table.getByRole('textbox', { name: '4행 1열' })).toHaveValue('둘째');
  await page.getByRole('button', { name: '내용에 맞춤' }).click();
  const downloadEvent = page.waitForEvent('download');
  await page.locator('.viewer-download-button.pdf').click();
  await page.getByRole('dialog', { name: 'PDF 다운로드 미리보기' }).getByRole('button', { name: '확인' }).click();
  const download = await downloadEvent;
  const bytes = await readFile(await download.path());
  const saved = await readPdfTables({ arrayBuffer: async () => bytes });
  const renderedPdf = await getDocument({ data: new Uint8Array(bytes) }).promise;
  const renderedText = (await (await renderedPdf.getPage(1)).getTextContent()).items.map((item) => item.str).join(' ');
  expect(renderedText).toContain('제목');
  expect(renderedText).toContain('둘째');
  expect(saved).toHaveLength(1);
  expect(saved[0].rows).toBe(4);
  expect(saved[0].spans).toHaveLength(1);
  expect(saved[0].cellStyles[3].bold).toBe(true);
  expect(saved[0].cellStyles[3].align).toBe('right');
  expect(saved[0].cells[9]).toBe('둘째');
  await page.goto('/');
  await page.locator('input[type="file"]').first().setInputFiles({ name: 'table-saved.pdf', mimeType: 'application/pdf', buffer: bytes });
  const reopened = page.locator('.pdf-page[data-page-number="1"]');
  await expect(reopened.locator('.textLayer')).toHaveAttribute('data-rendered', 'true');
  await page.locator('.pdf-edit-mode-toggle button').last().click();
  await reopened.locator('.pdf-table-object').click();
  await expect(reopened.getByRole('textbox', { name: '4행 1열' })).toHaveValue('둘째');
});

test('table track handles, insertion, splitting, and Tab navigation work', async ({ page }) => {
  test.setTimeout(120_000);
  const source = await PDFDocument.create();
  source.addPage([500, 500]);
  await page.goto('/');
  await page.locator('input[type="file"]').first().setInputFiles({
    name: 'table-controls.pdf', mimeType: 'application/pdf', buffer: Buffer.from(await source.save())
  });
  const pdfPage = page.locator('.pdf-page[data-page-number="1"]');
  await expect(pdfPage.locator('.textLayer')).toHaveAttribute('data-rendered', 'true');
  await page.locator('.pdf-edit-mode-toggle button').last().click();
  await page.getByRole('button', { name: '표 추가' }).click();
  const bounds = await pdfPage.boundingBox();
  const scale = bounds.width / 500;
  await page.mouse.move(bounds.x + 80 * scale, bounds.y + 80 * scale);
  await page.mouse.down();
  await page.mouse.move(bounds.x + 330 * scale, bounds.y + 230 * scale, { steps: 8 });
  await page.mouse.up();
  const table = pdfPage.locator('.pdf-table-object');
  const first = table.getByRole('textbox', { name: '1행 1열' });
  await first.click();
  await first.fill('시작');
  await first.press('Tab');
  await expect(table.getByRole('textbox', { name: '1행 2열' })).toBeFocused();
  await page.getByRole('button', { name: '아래에 행' }).click();
  await expect(table.getByRole('textbox', { name: '4행 1열' })).toBeVisible();
  await page.getByRole('button', { name: '오른쪽에 열' }).click();
  await expect(table.getByRole('textbox', { name: '1행 4열' })).toBeVisible();
  await table.getByRole('textbox', { name: '1행 1열' }).click();
  await page.getByRole('button', { name: '셀 좌우 분할' }).click();
  await expect(table.getByRole('textbox', { name: '1행 5열' })).toBeVisible();
  const handle = table.locator('.pdf-table-column-handle').first();
  await page.getByRole('tab', { name: '크기' }).click();
  const before = await page.getByLabel('선택한 열 너비').inputValue();
  const handleBounds = await handle.boundingBox();
  await page.mouse.move(handleBounds.x + handleBounds.width / 2, handleBounds.y + 20);
  await page.mouse.down();
  await page.mouse.move(handleBounds.x + handleBounds.width / 2 + 18, handleBounds.y + 20, { steps: 5 });
  await page.mouse.up();
  await expect.poll(async () => page.getByLabel('선택한 열 너비').inputValue()).not.toBe(before);
  const downloadEvent = page.waitForEvent('download');
  await page.locator('.viewer-download-button.pdf').click();
  await page.getByRole('dialog', { name: 'PDF 다운로드 미리보기' }).getByRole('button', { name: '확인' }).click();
  const bytes = await readFile(await (await downloadEvent).path());
  const saved = await readPdfTables({ arrayBuffer: async () => bytes });
  expect(saved[0].rows).toBe(4);
  expect(saved[0].columns).toBe(5);
  expect(saved[0].spans.length).toBeGreaterThan(0);
  await page.goto('/');
  await page.locator('input[type="file"]').first().setInputFiles({ name: 'table-controls-saved.pdf', mimeType: 'application/pdf', buffer: bytes });
  const reopened = page.locator('.pdf-page[data-page-number="1"]');
  await expect(reopened.locator('.textLayer')).toHaveAttribute('data-rendered', 'true');
  await page.locator('.pdf-edit-mode-toggle button').last().click();
  await reopened.locator('.pdf-table-object').click();
  await expect(reopened.getByRole('textbox', { name: '1행 5열' })).toBeVisible();
});

test('dragging cells applies one color and merges the selected range', async ({ page }) => {
  test.setTimeout(120_000);
  const source = await PDFDocument.create();
  source.addPage([500, 500]);
  await page.goto('/');
  await page.locator('input[type="file"]').first().setInputFiles({ name: 'table-drag.pdf', mimeType: 'application/pdf', buffer: Buffer.from(await source.save()) });
  const pdfPage = page.locator('.pdf-page[data-page-number="1"]');
  await expect(pdfPage.locator('.textLayer')).toHaveAttribute('data-rendered', 'true');
  await page.locator('.pdf-edit-mode-toggle button').last().click();
  await page.getByRole('button', { name: '표 추가' }).click();
  const bounds = await pdfPage.boundingBox();
  const scale = bounds.width / 500;
  await page.mouse.move(bounds.x + 80 * scale, bounds.y + 80 * scale);
  await page.mouse.down();
  await page.mouse.move(bounds.x + 330 * scale, bounds.y + 230 * scale, { steps: 8 });
  await page.mouse.up();
  const table = pdfPage.locator('.pdf-table-object');
  await expect(page.locator('.pdf-table-toolbar')).toHaveCount(0);
  const start = await table.getByRole('textbox', { name: '2행 1열' }).boundingBox();
  const end = await table.getByRole('textbox', { name: '3행 2열' }).boundingBox();
  await page.mouse.move(start.x + start.width / 2, start.y + start.height / 2);
  await page.mouse.down();
  await page.mouse.move(end.x + end.width / 2, end.y + end.height / 2, { steps: 12 });
  await page.mouse.up();
  await expect(page.locator('.pdf-table-toolbar')).toContainText('2~3행, 1~2열');
  await page.getByRole('tab', { name: '셀 서식' }).click();
  await page.getByLabel('셀 배경색').fill('#eac8ff');
  await page.getByRole('tab', { name: '행·열' }).click();
  await page.getByRole('button', { name: '셀 병합' }).click();
  await expect(table.locator('.pdf-table-cell')).toHaveCount(6);
  const downloadEvent = page.waitForEvent('download');
  await page.locator('.viewer-download-button.pdf').click();
  await page.getByRole('dialog', { name: 'PDF 다운로드 미리보기' }).getByRole('button', { name: '확인' }).click();
  const bytes = await readFile(await (await downloadEvent).path());
  const [saved] = await readPdfTables({ arrayBuffer: async () => bytes });
  expect(saved.spans).toContainEqual({ row: 1, column: 0, rowSpan: 2, colSpan: 2 });
  for (const index of [3, 4, 6, 7]) expect(saved.cellStyles[index].fill).toBe('#eac8ff');
  await pdfPage.click({ position: { x: 10, y: 10 } });
  await expect(page.locator('.pdf-table-toolbar')).toHaveCount(0);
});
